---

- hosts: tag_Name_ThoughtWorksNginx4

  become: yes
  become_user: "root"
  become_method: sudo

  tasks:

    - name: "create a root directory for nginx"
      file: path="/etc/tier2" state=directory mode=0755
      tags:
        - tier2_dir

	- name: "create a test file"
	  copy: src="files/a.txt" dest="/etc/tier2/"

    - name: "create a default nginx conf file"
      copy: src="files/nginx2" dest="/etc/nginx/sites-available/default"
